# Generated by Django 4.0 on 2022-02-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category_event_features_review_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='events.event'),
        ),
    ]
